spring:
  application:
    name: book.service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: pass
  liquibase:
    change-log: classpath:/liquibase/master.xml
