spring:
  application:
    name: book.service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bookService
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/liquibase/master.xml
