services:
  postgres_book:
    image: postgres:16
    container_name: postgres_book
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres_reservation:
    image: postgres:16
    container_name: postgres_reservation
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: reservation
    ports:
      - "5433:5432"
    volumes:
      - pgdata_reservation:/var/lib/postgresql/data

volumes:
  pgdata:
  pgdata_reservation: